Importing ibraries

In [48]:
import pandas as pd
import numpy as np

Data Loading & Date Parsing

In [49]:
#loading csv file
df = pd.read_csv("Data/ethiopia.csv")

In [50]:
#Adding a Country column
df["Country"] = "Ethiopia"

In [51]:
#Convering YEAR and DOY into a proper datetime column
df["date"] = pd.to_datetime(df["YEAR"] * 1000 + df["DOY"], format="%Y%j")

In [52]:
#Extract Month as a separate column for seasonal analysis
df["month"] = df["date"].dt.month

In [53]:
#checking if the changes re actually made
df[["YEAR", "DOY", "date", "month", "Country"]].head()

   YEAR  DOY       date  month   Country
0  2015    1 2015-01-01      1  Ethiopia
1  2015    2 2015-01-02      1  Ethiopia
2  2015    3 2015-01-03      1  Ethiopia
3  2015    4 2015-01-04      1  Ethiopia
4  2015    5 2015-01-05      1  Ethiopia

Summary Statistics & Missing-Value Report

In [54]:
#Replace -999 with NaN (Do this first!)
df.replace(-999, np.nan, inplace=True)

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,T2M_RANGE,PRECTOTCORR,RH2M,WS2M,WS2M_MAX,PS,QV2M,Country,date,month
0,2015,1,11.73,22.75,3.44,19.31,0.00,41.79,2.73,5.07,77.13,4.00,Ethiopia,2015-01-01,1
1,2015,2,12.30,24.01,4.09,19.92,0.00,33.29,2.39,4.19,77.14,3.35,Ethiopia,2015-01-02,1
2,2015,3,12.49,24.17,3.97,20.20,0.00,33.83,1.77,2.76,77.11,3.43,Ethiopia,2015-01-03,1
3,2015,4,14.08,23.78,6.90,16.88,0.00,38.84,0.87,1.28,77.07,4.60,Ethiopia,2015-01-04,1
4,2015,5,14.06,23.15,7.32,15.83,0.00,47.07,1.34,2.14,77.01,5.58,Ethiopia,2015-01-05,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4103,2026,86,16.99,24.29,11.80,12.49,5.27,73.87,1.79,3.09,76.60,11.17,Ethiopia,2026-03-27,3
4104,2026,87,15.29,19.58,12.08,7.50,6.46,80.85,1.13,2.35,76.59,11.29,Ethiopia,2026-03-28,3
4105,2026,88,16.28,22.34,11.69,10.65,9.53,77.96,1.30,2.39,76.48,11.42,Ethiopia,2026-03-29,3
4106,2026,89,17.66,25.31,11.08,14.23,0.85,68.88,2.02,3.80,76.44,10.64,Ethiopia,2026-03-30,3
4107,2026,90,18.25,26.36,12.14,14.22,0.40,63.95,2.18,3.64,76.47,10.14,Ethiopia,2026-03-31,3

In [55]:
#Checking for duplicates
duplicate_count = df.duplicated().sum()
print(f"Total duplicate rows found: {duplicate_count}")

Total duplicate rows found: 0

In [56]:
###Drop duplicates if any exist
if duplicate_count > 0:
    df.drop_duplicates(inplace=True)
    print("Duplicates removed.")

In [57]:
#descriptive statistics for all numeric columns
df.describe()

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,T2M_RANGE,PRECTOTCORR,RH2M,WS2M,WS2M_MAX,PS,QV2M,date,month
count,4108.000000,4108.000000,4108.00000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108,4108.000000
mean,2020.131451,180.121227,16.06850,23.199175,10.227544,12.971631,3.633795,68.408588,1.979998,3.575246,77.037529,9.697724,2020-08-15 12:00:00,6.423564
min,2015.000000,1.000000,10.03000,15.650000,1.170000,3.560000,0.000000,14.420000,0.460000,0.790000,76.360000,2.120000,2015-01-01 00:00:00,1.000000
25%,2017.000000,86.000000,14.82000,21.110000,8.417500,9.830000,0.020000,59.030000,1.407500,2.720000,76.980000,8.070000,2017-10-23 18:00:00,3.000000
50%,2020.000000,179.000000,16.04000,22.740000,10.990000,13.030000,0.820000,71.120000,1.970000,3.530000,77.040000,10.270000,2020-08-15 12:00:00,6.000000
75%,2023.000000,272.000000,17.36000,25.170000,12.220000,16.020000,4.580000,80.802500,2.480000,4.370000,77.100000,11.710000,2023-06-08 06:00:00,9.000000
max,2026.000000,366.000000,21.53000,30.930000,15.680000,23.240000,82.300000,91.930000,4.130000,7.490000,77.370000,13.520000,2026-03-31 00:00:00,12.000000
std,3.248907,106.294767,1.89805,2.751471,2.607256,3.821239,6.289061,14.735838,0.689093,1.123721,0.099484,2.362462,NaN,3.477046

This section gives as the average,minumum,maximum,std,and interquatile values... of each column giving as a general understandng of the data.   For instance the mean daily air temperature at 2 meters above the surface is 16 degrees as observed in the output.

In [58]:
#Compute null counts and percentages
null_counts = df.isna().sum()
null_percentages = (null_counts / len(df)) * 100

# Create a summary table
missing_report = pd.DataFrame({
    'Null Count': null_counts,
    'Percentage (%)': null_percentages
    })

In [59]:
# Display only columns with missing data
print("Missing Data Report:")
print(missing_report[missing_report['Null Count'] > 0])

Missing Data Report:
Empty DataFrame
Columns: [Null Count, Percentage (%)]
Index: []

In [60]:
# List columns with > 5% nulls
high_nulls = null_percentages[null_percentages > 5]
if not high_nulls.empty:
    print("\nColumns with > 5% Missing Data:")
    for col, val in high_nulls.items():
        print(f"- {col}: {val:.2f}%")
else:
    print("\nNo columns exceed 5% missing data.")

No columns exceed 5% missing data.

Since no columns exceed the 5% null threshold, we can proceed with full confidence in our statistial analysis work.

In [61]:
#Outlier Detection & Basic Cleaning
from scipy import stats

# Columns to check for outliers
weather_cols = ['T2M', 'T2M_MAX', 'T2M_MIN', 'PRECTOTCORR', 'RH2M', 'WS2M', 'WS2M_MAX']

# Calculate absolute Z-scores
z_scores = np.abs(stats.zscore(df[weather_cols]))

# Create a boolean mask where any column has |Z| > 3
outlier_mask = (z_scores > 3).any(axis=1)
outlier_count = outlier_mask.sum()

print(f"Total rows flagged as outliers (|Z| > 3): {outlier_count}")

Total rows flagged as outliers (|Z| > 3): 132

It would be better to keep the outliers since these extreme values tells us a sudden spike in the weather condition and is no an error made by measurement.And this extreme weather conditions are naturally expected.

In [62]:
#List of all weather-related variables to be filled
weather_variables = [
    'T2M', 'T2M_MAX', 'T2M_MIN', 'T2M_RANGE', 
    'PRECTOTCORR', 'RH2M', 'WS2M', 'WS2M_MAX', 
    'PS', 'QV2M'
]

In [63]:
#Drop rows with >30% missing values
# (If a row has less than 70% of the columns filled, we discard it as unreliable)
initial_rows = len(df)
df.dropna(thresh=int(len(df.columns) * 0.7), inplace=True)
dropped_rows = initial_rows - len(df)

#  Apply forward-fill to the specific weather columns
# This propagates the last valid observation forward to next valid
df[weather_variables] = df[weather_variables].ffill()

print(f"Cleaning complete.")
print(f"Rows dropped (threshold < 70%): {dropped_rows}")

Cleaning complete.
Rows dropped (threshold < 70%): 0

In [64]:
df.to_csv('Data/ethiopia_clean.csv', index=False)
print("Data saved to Data/ethiopia_clean.csv")

Data saved to Data/ethiopia_clean.csv